import React, { useState } from 'react';
import { Award, Briefcase, ChevronRight, Save, Zap, Compass, DollarSign, CheckCircle } from 'lucide-react';

const SkillProfiler = ({ apiBaseUrl, onPredictionComplete, mockScore }) => {
  const [profile, setProfile] = useState({
    name: '',
    branch: 'CSE',
    cgpa: 7.5,
    java: 5,
    python: 5,
    web_dev: 5,
    dsa: 5,
    communication: 5,
    leadership: 5,
    projects: 2,
    internships: 1,
    certifications: 1
  });

  const [loading, setLoading] = useState(false);
  const [prediction, setPrediction] = useState(null);
  const [saveSuccess, setSaveSuccess] = useState(false);

  const handleSliderChange = (key, value) => {
    setProfile(prev => ({
      ...prev,
      [key]: value
    }));
  };

  const handleTextChange = (key, value) => {
    setProfile(prev => ({
      ...prev,
      [key]: value
    }));
  };

  const handlePredict = async (e) => {
    if (e) e.preventDefault();
    if (!profile.name.trim()) {
      alert("Please enter a student name first.");
      return;
    }
    
    setLoading(true);
    setSaveSuccess(false);
    
    try {
      const res = await fetch(`${apiBaseUrl}/api/predict`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          ...profile,
          mock_score: mockScore
        })
      });
      
      if (res.ok) {
        const data = await res.json();
        setPrediction(data);
        if (onPredictionComplete) {
          onPredictionComplete({
            role: data.recommended_role,
            lpa: data.package_lpa,
            skillGap: data.skill_gap,
            requiredSkills: data.required_skills,
            roadmap: data.learning_path,
            companies: data.companies,
            studentProfile: profile
          });
        }
      }
    } catch (err) {
      console.error("Prediction failed:", err);
      alert("Error making prediction. Ensure the backend server is running.");
    } finally {
      setLoading(false);
    }
  };

  const handleSaveToDatabase = async () => {
    if (!prediction) return;
    try {
      const res = await fetch(`${apiBaseUrl}/api/students`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          ...profile,
          recommended_role: prediction.recommended_role,
          package_lpa: prediction.package_lpa,
          career_interest: prediction.recommended_role
        })
      });
      if (res.ok) {
        setSaveSuccess(true);
      }
    } catch (err) {
      console.error("Save profile failed:", err);
    }
  };

  const getLpaFactors = () => {
    if (!prediction) return [];
    const factors = [];
    if (profile.cgpa >= 8.5) factors.push({ name: "High CGPA (>= 8.5)", value: "+1.5 LPA", type: "positive" });
    else if (profile.cgpa < 7.0) factors.push({ name: "Low CGPA (< 7.0)", value: "-1.0 LPA", type: "negative" });
    
    if (profile.dsa >= 8) factors.push({ name: "Strong DSA Foundation", value: "+2.0 LPA", type: "positive" });
    if (profile.projects >= 3) factors.push({ name: "Project Portfolio (3+ projects)", value: "+1.5 LPA", type: "positive" });
    if (profile.internships >= 1) factors.push({ name: "Prior Internship Experience", value: "+1.5 LPA", type: "positive" });
    if (profile.communication >= 8 && profile.leadership >= 8) factors.push({ name: "Excellent Soft Skills", value: "+1.0 LPA", type: "positive" });
    
    if (mockScore >= 80) factors.push({ name: "Excellent Mock Test Score", value: "+1.5 LPA", type: "positive" });
    else if (mockScore > 0 && mockScore < 50) factors.push({ name: "Weak Mock Test Score", value: "-0.8 LPA", type: "negative" });
    
    if (factors.length === 0) {
      factors.push({ name: "Base Entry Level Standard", value: "Standard Rate", type: "neutral" });
    }
    return factors;
  };

  return (
    <div className="animate-fade-in grid-profiler-layout">
      {/* LEFT PANEL: Output & ML Recommendation Hero */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
        {prediction ? (
          <div className="neo-card neo-card-purple" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', gap: '24px', height: '100%' }}>
            <div style={{ width: '100%' }}>
              <span className="neo-badge neo-badge-yellow">
                RECOMMENDED PATH
              </span>
              <h2 style={{ fontSize: '26px', fontWeight: 900, color: '#fff', textTransform: 'uppercase', marginTop: '8px', textShadow: '2px 2px 0px #000' }}>
                {prediction.recommended_role}
              </h2>
              <p style={{ fontSize: '12px', fontWeight: 800, color: '#e2e8f0' }}>Generated by Scikit-Learn Random Forest Model</p>
            </div>

            {/* 3D Circular Gauge */}
            <div style={{ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'center', width: '180px', height: '180px', backgroundColor: '#000', border: '4px solid #000', borderRadius: '50%', boxShadow: '6px 6px 0px #000' }}>
              <svg style={{ width: '100%', height: '100%', transform: 'rotate(-90deg)' }} viewBox="0 0 100 100">
                <circle cx="50" cy="50" r="40" stroke="#1e293b" strokeWidth="10" fill="transparent" />
                <circle 
                  cx="50" cy="50" r="40" 
                  stroke="#00ff66" 
                  strokeWidth="10" fill="transparent"
                  strokeDasharray={`${2 * Math.PI * 40}`}
                  strokeDashoffset={`${2 * Math.PI * 40 * (1 - Math.min(prediction.package_lpa, 25) / 25)}`}
                  strokeLinecap="round"
                />
              </svg>
              <div style={{ position: 'absolute', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
                <span style={{ fontSize: '32px', fontWeight: 900, color: '#ffe600', textShadow: '2px 2px 0px #000' }}>
                  ₹{prediction.package_lpa}
                </span>
                <span style={{ fontSize: '10px', fontWeight: 900, color: '#00ff66', textTransform: 'uppercase', letterSpacing: '0.1em', marginTop: '2px', backgroundColor: '#000', padding: '2px 8px', borderRadius: '4px', border: '1px solid #334155' }}>
                  ESTIMATED LPA
                </span>
              </div>
            </div>

            {/* Factor breakdown */}
            <div style={{ width: '100%', textAlign: 'left', backgroundColor: 'rgba(0,0,0,0.6)', padding: '16px', borderRadius: '12px', border: '3px solid #000', boxShadow: '3px 3px 0px #000' }}>
              <h4 style={{ fontSize: '12px', fontWeight: 900, color: '#ffe600', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '8px' }}>Salary Impact Factors</h4>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', maxHeight: '160px', overflowY: 'auto', fontWeight: 800 }}>
                {getLpaFactors().map((factor, idx) => (
                  <div key={idx} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '11px', backgroundColor: 'rgba(0,0,0,0.4)', padding: '6px 10px', borderRadius: '4px', border: '1px solid #1e293b' }}>
                    <span style={{ color: '#cbd5e1' }}>{factor.name}</span>
                    <span style={{ fontWeight: 900, color: factor.type === 'positive' ? '#00ff66' : factor.type === 'negative' ? '#ff3344' : '#94a3b8' }}>{factor.value}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Target Companies */}
            <div style={{ width: '100%', textAlign: 'left' }}>
              <h4 style={{ fontSize: '12px', color: '#fff', fontWeight: 900, textTransform: 'uppercase', marginBottom: '8px' }}>Top Target Companies</h4>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                {prediction.companies.map((company, index) => (
                  <span key={index} className="neo-badge neo-badge-cyan" style={{ fontSize: '10px' }}>
                    {company}
                  </span>
                ))}
              </div>
            </div>

            {/* Save Profile Button */}
            <button 
              type="button" 
              onClick={handleSaveToDatabase} 
              disabled={saveSuccess}
              className="neo-btn neo-btn-green"
              style={{ width: '100%', justifyContent: 'center', padding: '12px', fontSize: '12px', marginTop: 'auto' }}
            >
              <Save size={16} />
              <span>{saveSuccess ? "PROFILE SAVED TO DB" : "SAVE TO DATABASE"}</span>
            </button>
          </div>
        ) : (
          <div className="neo-card" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', gap: '24px', height: '100%', padding: '64px 24px' }}>
            <div style={{ width: '70px', height: '70px', backgroundColor: '#ffe600', color: '#000', border: '3px solid #000', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '4px 4px 0px #000' }}>
              <DollarSign size={36} />
            </div>
            <div>
              <h3 style={{ fontSize: '20px', fontWeight: 900, textTransform: 'uppercase' }}>Prediction Waiting</h3>
              <p style={{ fontSize: '12px', fontWeight: 800, color: '#94a3b8', maxWidth: '280px', margin: '4px auto 0' }}>Fill in student details on the right panel and click predict to trigger ML algorithm.</p>
            </div>
          </div>
        )}
      </div>

      {/* RIGHT PANEL: Input Form & Skill Sliders */}
      <form onSubmit={handlePredict} className="neo-card" style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
        <div>
          <div className="neo-badge neo-badge-yellow" style={{ marginBottom: '8px' }}>
            <Compass size={14} />
            <span>AI CAPABILITY INPUT</span>
          </div>
          <h2 style={{ fontSize: '22px', fontWeight: 900, textTransform: 'uppercase' }}>Student Profile Details</h2>
          <p style={{ fontSize: '12px', fontWeight: 800, color: '#94a3b8', marginTop: '4px' }}>Provide academic metrics and self-assessed ratings to trigger ML recommendation model</p>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px' }}>
          <div>
            <label className="neo-label">Full Name</label>
            <input 
              type="text" 
              placeholder="E.G. RAHUL KUMAR" 
              required
              value={profile.name}
              onChange={(e) => handleTextChange('name', e.target.value)}
              className="neo-input"
              style={{ textTransform: 'uppercase' }}
            />
          </div>
          <div>
            <label className="neo-label">Academic Branch</label>
            <select 
              value={profile.branch} 
              onChange={(e) => handleTextChange('branch', e.target.value)}
              className="neo-input"
              style={{ textTransform: 'uppercase' }}
            >
              <option value="CSE">Computer Science & Engineering (CSE)</option>
              <option value="IT">Information Technology (IT)</option>
              <option value="ECE">Electronics & Communication (ECE)</option>
              <option value="EEE">Electrical & Electronics (EEE)</option>
              <option value="MECH">Mechanical Engineering</option>
            </select>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))', gap: '16px' }}>
          <div style={{ gridColumn: 'span 2' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
              <label className="neo-label" style={{ marginBottom: 0 }}>CGPA SCORE</label>
              <span className="neo-badge neo-badge-yellow" style={{ fontSize: '10px' }}>{profile.cgpa.toFixed(1)}</span>
            </div>
            <input 
              type="range" 
              min="5.0" 
              max="10.0" 
              step="0.1" 
              value={profile.cgpa}
              onChange={(e) => handleSliderChange('cgpa', parseFloat(e.target.value))}
              className="neo-slider"
            />
          </div>
          <div>
            <label className="neo-label">Projects</label>
            <input 
              type="number" 
              min="0" 
              max="10" 
              value={profile.projects}
              onChange={(e) => handleSliderChange('projects', parseInt(e.target.value) || 0)}
              className="neo-input"
              style={{ textAlign: 'center', fontWeight: 900 }}
            />
          </div>
          <div>
            <label className="neo-label">Internships</label>
            <input 
              type="number" 
              min="0" 
              max="5" 
              value={profile.internships}
              onChange={(e) => handleSliderChange('internships', parseInt(e.target.value) || 0)}
              className="neo-input"
              style={{ textAlign: 'center', fontWeight: 900 }}
            />
          </div>
        </div>

        {/* Skills Sliders Subgrid */}
        <div style={{ borderTop: '3px solid #000', paddingTop: '20px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <h3 style={{ fontSize: '12px', fontWeight: 900, color: '#e2e8f0', textTransform: 'uppercase', backgroundColor: '#25283a', padding: '8px 12px', borderRadius: '6px', border: '1px solid #000', boxShadow: '2px 2px 0px #000' }}>
            Skill Self Ratings (Scale 1 - 10)
          </h3>
          
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '20px' }}>
            {/* Java */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', fontWeight: 900 }}>
                <span style={{ color: '#cbd5e1' }}>Java & OOP Design</span>
                <span className="neo-badge neo-badge-cyan" style={{ fontSize: '10px' }}>{profile.java}/10</span>
              </div>
              <input 
                type="range" min="1" max="10" value={profile.java} 
                onChange={(e) => handleSliderChange('java', parseInt(e.target.value))}
                className="neo-slider"
              />
            </div>

            {/* Python */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', fontWeight: 900 }}>
                <span style={{ color: '#cbd5e1' }}>Python & Data Science</span>
                <span className="neo-badge neo-badge-cyan" style={{ fontSize: '10px' }}>{profile.python}/10</span>
              </div>
              <input 
                type="range" min="1" max="10" value={profile.python} 
                onChange={(e) => handleSliderChange('python', parseInt(e.target.value))}
                className="neo-slider"
              />
            </div>

            {/* Web Dev */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', fontWeight: 900 }}>
                <span style={{ color: '#cbd5e1' }}>Web Dev (React/Node)</span>
                <span className="neo-badge neo-badge-cyan" style={{ fontSize: '10px' }}>{profile.web_dev}/10</span>
              </div>
              <input 
                type="range" min="1" max="10" value={profile.web_dev} 
                onChange={(e) => handleSliderChange('web_dev', parseInt(e.target.value))}
                className="neo-slider"
              />
            </div>

            {/* DSA */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', fontWeight: 900 }}>
                <span style={{ color: '#cbd5e1' }}>Data Structures & Algo</span>
                <span className="neo-badge neo-badge-cyan" style={{ fontSize: '10px' }}>{profile.dsa}/10</span>
              </div>
              <input 
                type="range" min="1" max="10" value={profile.dsa} 
                onChange={(e) => handleSliderChange('dsa', parseInt(e.target.value))}
                className="neo-slider"
              />
            </div>

            {/* Communication */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', fontWeight: 900 }}>
                <span style={{ color: '#cbd5e1' }}>Communication Skills</span>
                <span className="neo-badge neo-badge-cyan" style={{ fontSize: '10px' }}>{profile.communication}/10</span>
              </div>
              <input 
                type="range" min="1" max="10" value={profile.communication} 
                onChange={(e) => handleSliderChange('communication', parseInt(e.target.value))}
                className="neo-slider"
              />
            </div>

            {/* Leadership */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', fontWeight: 900 }}>
                <span style={{ color: '#cbd5e1' }}>Leadership & Management</span>
                <span className="neo-badge neo-badge-cyan" style={{ fontSize: '10px' }}>{profile.leadership}/10</span>
              </div>
              <input 
                type="range" min="1" max="10" value={profile.leadership} 
                onChange={(e) => handleSliderChange('leadership', parseInt(e.target.value))}
                className="neo-slider"
              />
            </div>
          </div>
        </div>

        <button type="submit" disabled={loading} className="neo-btn neo-btn-yellow" style={{ width: '100%', padding: '16px', fontSize: '14px', marginTop: '12px' }}>
          {loading ? (
            <span>Processing ML Algorithm...</span>
          ) : (
            <>
              <Zap size={20} />
              <span>PREDICT CAREER PATH & LPA</span>
            </>
          )}
        </button>
      </form>
    </div>
  );
};

export default SkillProfiler;
